### ISSUE TITLE
commands for RRS 

### ISSUE THREAD

**Issue by onezetty** [ZeroDragon/cryptoAlerter#3]
I think the commands for the "/news" options can be "short", to make more efficient the news feeds request: 

/news l (list)
/news s (subscribe) <list-item>
/news d (unsubscribe) <list-item>
/news f (from) <list-item> [items]
/news a (all)

example: 

/news s criptoblog-com/feed

**Comment by ZeroDragon** [comment]
RSS has been deprecated on the bot
