### ISSUE TITLE
Create multi profile UI

### ISSUE THREAD

**Issue by Jzarecta** [ZeroDragon/cryptoAlerter#5]
Tracking several coins with specific alerts could make out of different complex scenarios. Would be nice to have this scenarios 'froze' and stored as opposed of being lost by a trade overwrite. 

**Profiles** would be a solution to be able to save that information while performing a simple alert for a bitcoin-fiat trade.

**Comment by ZeroDragon** [comment]
this is kinda the new approach in the bot. enhancements can be done later
